select * FROM LIS.LDOOOO WHERE QUERYTEMPLATE='${oaNo}';
DELETE FROM LIS.LDOOOO WHERE QUERYTEMPLATE='${oaNo}';
INSERT INTO LIS.LDOOOO
(QUERYTEMPLATE, QUERYSQL, REMARK, SPAREFIELD1, SPAREFIELD2, SPAREFIELD3, SYSMAKEDATE, SYSMODIFYDATE)
VALUES('${oaNo}', '${sqlScript}', '${content}-(${author})', NULL, '${title}', NULL, TIMESTAMP '${sysdate}', TIMESTAMP '${sysdate}');
select * FROM LIS.LDOOOO WHERE QUERYTEMPLATE='${oaNo}';
